package main

import "fmt"

// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// a, b
// _, a, b
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

func main() {
	//fmt.Println(SumEvenFibSequence(100))
	fmt.Println(RecFibSequence(10))
}

func SumEvenFibSequence(limit int) int {
	var sum int
	a := 1
	b := 2
	for a < limit {
		if a%2 == 0 {
			sum += a
		}
		absum := a + b
		a = b
		b = absum
	}
	return sum
}

// 0, 1
func RecFibSequence(n int) int {
	if n == 0 {
		return 0
	}
	if n == 1 {
		return 1
	}
	return RecFibSequence(n-1) + RecFibSequence(n-2)
	// RecFibSequence(b, a+b, limit)
}
